# Generated by Django 4.0.4 on 2024-09-30 08:51

from django.db import migrations
from sso.models import ChainConfig

def seed_data(apps, schema_editor):
    chains = [
        {
            'id': 1,
            'name': 'BNB Mainnet',
            'chain_id': '56',
            'rpc': 'https://bsc-dataseed.bnbchain.org',
        },
        {
            'id': 2,
            'name': 'BNB Testnet',
            'chain_id': '97',
            'rpc': 'https://data-seed-prebsc-1-s1.bnbchain.org:8545',
        },
        {
            'id': 3,
            'name': 'AVAX Mainnet',
            'chain_id': '43114',
            'rpc': 'https://api.avax.network/ext/bc/C/rpc',
        },
        {
            'id': 4,
            'name': 'AVAX Testnet',
            'chain_id': '43113',
            'rpc': 'https://api.avax-test.network/ext/bc/C/rpc',
        },
    ]
    for item in chains:
        cli = ChainConfig(
            id=item['id'],
            name=item['name'],
            chain_id=item['chain_id'],
            rpc=item['rpc'],
        )
        cli.save()

def reverse_data(apps, schema_editor):
    schema_editor.execute("DELETE FROM chain_config")

class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0002_auto_20240930_0835'),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_data)
    ]
